// Generated by Cypress Author on 2026-07-23.
import { describe, expect, it } from 'vitest';
import { plaintextMarkdownFromClipboard } from './markdown-paste';

function clipboard(data: Record<string, string>) {
  return {
    getData(type: string): string {
      return data[type] ?? '';
    }
  };
}

describe('Markdown clipboard routing', () => {
  it('plain Markdown table and code → routes the complete source to the Markdown parser', () => {
    const source = [
      '# BOAMP Corpus Profile',
      '',
      '| Item | Value |',
      '',
      '| --- | --- |',
      '',
      '| Input format | JSON |',
      '',
      '```sh',
      'go run ./cmd/zocco profile-boamp',
      '```',
      '',
      '- [x] Profilé'
    ].join('\r\n');

    const result = plaintextMarkdownFromClipboard(
      clipboard({ 'text/plain': source })
    );

    expect(result).toContain('| Item | Value |');
    expect(result).toContain('| Item | Value |\n| --- | --- |\n| Input format | JSON |');
    expect(result).toContain('```sh');
    expect(result).toContain('- [x] Profilé');
    expect(result).not.toContain('\r');
  });

  it('structured Markdown → takes priority over a parallel HTML flavor', () => {
    expect(
      plaintextMarkdownFromClipboard(
        clipboard({
          'text/plain': '# Titre',
          'text/html': '<h1>Titre</h1>'
        })
      )
    ).toBe('# Titre');
  });

  it('rich prose without Markdown syntax → leaves parsing to the HTML pipeline', () => {
    expect(
      plaintextMarkdownFromClipboard(
        clipboard({
          'text/plain': 'Titre',
          'text/html': '<h1>Titre</h1>'
        })
      )
    ).toBeNull();
  });
});
