// Generated by Cypress Author on 2026-07-23.
import { describe, expect, it } from 'vitest';
import type { vault } from '../../wailsjs/go/models';
import { canCloseExportDialog, pdfExportBlocker } from './pdf-export';

function options(overrides: Partial<vault.PDFExportOptionsInfo> = {}): vault.PDFExportOptionsInfo {
  return {
    available: true,
    browser: 'Chromium',
    unavailableReason: '',
    themes: [
      {
        id: 'classic',
        name: 'Classique',
        builtin: true,
        version: 1,
        page: {
          size: 'A4',
          orientation: 'portrait',
          margins: { top: 20, right: 18, bottom: 20, left: 18 }
        },
        typography: {
          family: 'serif',
          monoFamily: 'monospace',
          bodySizePt: 11,
          lineHeight: 1.5,
          headingScale: 1.25
        },
        colors: {
          text: '#202124',
          secondary: '#5f6368',
          accent: '#315c8c',
          codeBackground: '#f3f4f6'
        },
        options: { titlePage: false, metadata: true, pageNumbers: true }
      }
    ],
    warnings: [],
    ...overrides
  } as vault.PDFExportOptionsInfo;
}

describe('PDF export state', () => {
  it('browser absent → exposes the actionable unavailability reason', () => {
    expect(
      pdfExportBlocker({
        options: options({
          available: false,
          browser: '',
          unavailableReason: 'Installez Chromium ou Google Chrome.'
        }),
        activeNotePath: 'notes/note.md',
        encrypted: false,
        plaintextConfirmed: false
      })
    ).toBe('Installez Chromium ou Google Chrome.');
  });

  it('encrypted vault → requires plaintext confirmation', () => {
    expect(
      pdfExportBlocker({
        options: options(),
        activeNotePath: 'notes/secret.md',
        encrypted: true,
        plaintextConfirmed: false
      })
    ).toContain('en clair');
  });

  it('active note and valid theme → enables export', () => {
    expect(
      pdfExportBlocker({
        options: options(),
        activeNotePath: 'notes/note.md',
        encrypted: true,
        plaintextConfirmed: true
      })
    ).toBe('');
  });

  it('rendering in progress → prevents the dialog from closing', () => {
    expect(canCloseExportDialog(true)).toBe(false);
    expect(canCloseExportDialog(false)).toBe(true);
  });
});
